//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public string IdCliente { get; set; }
        public string CedulaRif { get; set; }
        public string RazonSocial { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> DiasCredito { get; set; }
        public Nullable<double> LimiteCredito { get; set; }
        public string Telefonos { get; set; }
        public string Contacto { get; set; }
        public string Email { get; set; }
        public string Codigo { get; set; }
        public string Categoria { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
