//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.ComprasIngredientes = new HashSet<ComprasIngrediente>();
        }
    
        public string IdCompra { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Numero { get; set; }
        public string NumeroControl { get; set; }
        public Nullable<double> MontoExento { get; set; }
        public Nullable<double> MontoGravable { get; set; }
        public Nullable<double> MontoIva { get; set; }
        public Nullable<double> MontoTotal { get; set; }
        public string CedulaRif { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<double> TasaIva { get; set; }
        public Nullable<double> MontoSinDerechoCredito { get; set; }
        public string IdUsuario { get; set; }
        public string Direccion { get; set; }
        public Nullable<bool> LibroInventarios { get; set; }
        public Nullable<bool> LibroCompras { get; set; }
        public Nullable<bool> ActualizacionCostos { get; set; }
        public Nullable<bool> IncluirLibroCompras { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public Nullable<double> MontoGravableB { get; set; }
        public Nullable<double> TasaIvaB { get; set; }
        public Nullable<double> MontoImpuestosLicores { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasIngrediente> ComprasIngredientes { get; set; }
    }
}
