//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprasIngrediente
    {
        public string IdCompraIngrediente { get; set; }
        public string IdCompra { get; set; }
        public string Ingrediente { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<double> TasaIva { get; set; }
        public Nullable<double> CostoIva { get; set; }
        public Nullable<double> CantidadNeta { get; set; }
        public Nullable<double> Total { get; set; }
        public string IdIngrediente { get; set; }
        public Nullable<double> ExistenciaAnterior { get; set; }
        public Nullable<double> ExistenciaNueva { get; set; }
        public string UnidadMedida { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> CostoNeto { get; set; }
        public string Grupo { get; set; }
    
        public virtual Compra Compra { get; set; }
    }
}
