//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.FacturasPlatos = new HashSet<FacturasPlato>();
        }
    
        public string IdFactura { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public string Numero { get; set; }
        public string NumeroOrden { get; set; }
        public string NumeroZ { get; set; }
        public string MaquinaFiscal { get; set; }
        public string IdCajero { get; set; }
        public string Cajero { get; set; }
        public string CedulaRif { get; set; }
        public string RazonSocial { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public Nullable<double> MontoExento { get; set; }
        public Nullable<double> MontoGravable { get; set; }
        public Nullable<double> MontoServicio { get; set; }
        public Nullable<double> TasaIva { get; set; }
        public Nullable<double> MontoIva { get; set; }
        public Nullable<double> MontoTotal { get; set; }
        public Nullable<double> Efectivo { get; set; }
        public Nullable<double> Cambio { get; set; }
        public Nullable<double> Cheque { get; set; }
        public Nullable<double> Tarjeta { get; set; }
        public Nullable<double> CestaTicket { get; set; }
        public Nullable<double> ConsumoInterno { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> Credito { get; set; }
        public Nullable<double> Saldo { get; set; }
        public Nullable<bool> LibroInventarios { get; set; }
        public Nullable<bool> LibroVentas { get; set; }
        public Nullable<bool> Inventarios { get; set; }
        public Nullable<bool> Anulado { get; set; }
        public string Mesonero { get; set; }
        public string Categoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasPlato> FacturasPlatos { get; set; }
    }
}
