//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impuesto
    {
        public int Id { get; set; }
        public string TipoImpuesto { get; set; }
        public Nullable<decimal> TasaNormal { get; set; }
        public Nullable<decimal> TasaReducida { get; set; }
        public string InicialesReducido { get; set; }
        public Nullable<decimal> TopeReduccion { get; set; }
        public Nullable<decimal> TasaReducida2 { get; set; }
        public string InicialesReducido2 { get; set; }
    }
}
