//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroVenta
    {
        public string IdLibroVentas { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Factura { get; set; }
        public string NumeroZ { get; set; }
        public string RegistroMaquinaFiscal { get; set; }
        public string RazonSocial { get; set; }
        public string CedulaRif { get; set; }
        public string Comprobante { get; set; }
        public string FacturaAfectada { get; set; }
        public string TipoOperacion { get; set; }
        public Nullable<double> MontoTotal { get; set; }
        public Nullable<double> MontoGravable { get; set; }
        public Nullable<double> MontoExento { get; set; }
        public Nullable<double> MontoIva { get; set; }
        public Nullable<double> TasaIva { get; set; }
        public Nullable<double> IvaRetenido { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public string Direccion { get; set; }
        public Nullable<double> MontoServicio { get; set; }
        public Nullable<double> MontoIvaContribuyentes { get; set; }
        public Nullable<double> MontoIvaNoContribuyentes { get; set; }
        public Nullable<double> MontoGravableContribuyentes { get; set; }
        public Nullable<double> MontoGravableNoContribuyentes { get; set; }
        public Nullable<double> TasaIvaContribuyentes { get; set; }
        public Nullable<double> TasaIvaNoContribuyentes { get; set; }
        public string Inicio { get; set; }
        public string Final { get; set; }
    }
}
