//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroInventario
    {
        public string IdLibroInventarios { get; set; }
        public Nullable<double> Inicio { get; set; }
        public Nullable<double> Entradas { get; set; }
        public Nullable<double> Salidas { get; set; }
        public Nullable<double> Final { get; set; }
        public Nullable<double> InventarioFisico { get; set; }
        public Nullable<double> Ajustes { get; set; }
        public Nullable<double> Costo { get; set; }
        public string IdProducto { get; set; }
        public string Producto { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
