//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesasAbiertasPlatosAnulado
    {
        public string IdPlatoEliminado { get; set; }
        public string IdCajero { get; set; }
        public string Cajero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string IdPlato { get; set; }
        public string Plato { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> PrecioIva { get; set; }
        public Nullable<double> Total { get; set; }
        public string Numero { get; set; }
        public string IdUsuario { get; set; }
        public string Mesa { get; set; }
        public string Mesonero { get; set; }
        public string Concepto { get; set; }
    }
}
