//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesasAbiertasPlato
    {
        public string IdMesaAbiertaPlato { get; set; }
        public string IdMesaAbierta { get; set; }
        public string Idplato { get; set; }
        public string Codigo { get; set; }
        public string Grupo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> TasaIva { get; set; }
        public Nullable<double> PrecioConIva { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Costo { get; set; }
        public string EnviarComanda { get; set; }
        public Nullable<double> TotalBase { get; set; }
    
        public virtual MesasAbierta MesasAbierta { get; set; }
    }
}
