//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesa
    {
        public string IdMesa { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<bool> CobraServicio { get; set; }
        public Nullable<double> Descuento { get; set; }
    }
}
