//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesonero
    {
        public string IdMesonero { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public Nullable<double> Puntos { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Direccion { get; set; }
        public string Telefonos { get; set; }
    }
}
