//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public string Empresa { get; set; }
        public string EmpresaRif { get; set; }
        public string EmpresaDireccion { get; set; }
        public string EmpresaTelefonos { get; set; }
        public string MaquinaFiscal { get; set; }
        public Nullable<double> TasaIva { get; set; }
        public string TipoIva { get; set; }
        public string PuertoImpresoraFiscal { get; set; }
        public string Ciudad { get; set; }
        public string Licencia { get; set; }
        public string ImprimirOrden { get; set; }
        public string ImprimirCorteCuenta { get; set; }
        public Nullable<bool> ColaImpresionFiscalActiva { get; set; }
        public string UsoImpresoraFiscal { get; set; }
        public Nullable<bool> SolicitarMesonero { get; set; }
        public Nullable<double> TasaIvaB { get; set; }
        public Nullable<double> PorcentajeRetencion { get; set; }
        public string PeriodoFiscal { get; set; }
        public Nullable<double> TasaIvaC { get; set; }
    }
}
