//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plato()
        {
            this.PlatosCombos = new HashSet<PlatosCombo>();
            this.PlatosComentarios = new HashSet<PlatosComentario>();
            this.PlatosContornos = new HashSet<PlatosContorno>();
            this.PlatosIngredientes = new HashSet<PlatosIngrediente>();
        }
    
        public string IdPlato { get; set; }
        public string Grupo { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> TasaIva { get; set; }
        public Nullable<double> PrecioConIva { get; set; }
        public Nullable<double> Precio2 { get; set; }
        public Nullable<double> PrecioConIva2 { get; set; }
        public string EnviarComanda { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<bool> MostrarMenu { get; set; }
        public string IdCombo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlatosCombo> PlatosCombos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlatosComentario> PlatosComentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlatosContorno> PlatosContornos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlatosIngrediente> PlatosIngredientes { get; set; }
    }
}
