//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatosCombo
    {
        public string IdPlatoCombo { get; set; }
        public string IdPlato { get; set; }
        public string Plato { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<double> TotalCosto { get; set; }
        public string IdCombo { get; set; }
    
        public virtual Plato Plato1 { get; set; }
    }
}
