//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatosIngrediente
    {
        public string IdPlatoIngrediente { get; set; }
        public string IdPlato { get; set; }
        public string IdIngrediente { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Raciones { get; set; }
        public Nullable<double> CostoRacion { get; set; }
        public string Ingrediente { get; set; }
        public string UnidadMedida { get; set; }
        public string IdPlatoPresentacion { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Plato Plato { get; set; }
    }
}
