//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatosContorno
    {
        public string IdPlatoContorno { get; set; }
        public string IdPlato { get; set; }
        public string Contorno { get; set; }
    
        public virtual Plato Plato { get; set; }
    }
}
