//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retencione
    {
        public string Id { get; set; }
        public Nullable<int> NumeroDeOperacion { get; set; }
        public string CedulaRif { get; set; }
        public string NombreRazonSocial { get; set; }
        public string PeriodoImpositivo { get; set; }
        public Nullable<System.DateTime> FechaDocumento { get; set; }
        public string TipoOperacion { get; set; }
        public string TipoDocumento { get; set; }
        public string RifAgenteRetencion { get; set; }
        public string NumeroDocumento { get; set; }
        public string NumeroControlDocumento { get; set; }
        public Nullable<double> MontoDocumento { get; set; }
        public Nullable<double> BaseImponible { get; set; }
        public Nullable<double> MontoIvaRetenido { get; set; }
        public string NumeroDocumentoAfectado { get; set; }
        public string NumeroComprobante { get; set; }
        public Nullable<double> MontoExentoIva { get; set; }
        public Nullable<double> Alicuota { get; set; }
        public string NumeroExpediente { get; set; }
        public Nullable<double> MontoIva { get; set; }
        public Nullable<System.DateTime> FechaComprobante { get; set; }
        public string Periodo { get; set; }
        public Nullable<double> PorcentajeRetencion { get; set; }
    }
}
