//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string IdUsuario { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string TipoUsuario { get; set; }
        public string Clave { get; set; }
        public string Direccion { get; set; }
        public string Telefonos { get; set; }
        public Nullable<bool> PuedeDarConsumoInterno { get; set; }
        public Nullable<bool> PuedeSepararCuentas { get; set; }
        public Nullable<bool> PuedePedirCorteDeCuenta { get; set; }
        public Nullable<bool> PuedeRegistrarPago { get; set; }
        public Nullable<bool> PuedeCambiarMesa { get; set; }
        public Nullable<bool> PuedeDarCreditos { get; set; }
        public Nullable<bool> ReporteX { get; set; }
        public Nullable<bool> ReporteZ { get; set; }
        public Nullable<bool> Vale { get; set; }
        public Nullable<bool> CierreDeCaja { get; set; }
        public Nullable<bool> ContarDinero { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> PuedeCambiarCantidad { get; set; }
        public Nullable<bool> PuedeCambiarPrecios { get; set; }
        public Nullable<int> Puntos { get; set; }
        public Nullable<bool> PuedeEliminarPlatos { get; set; }
        public string Codigo { get; set; }
    }
}
