//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vale
    {
        public string IdVale { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string IdCajero { get; set; }
        public string Concepto { get; set; }
        public Nullable<double> Monto { get; set; }
        public string Cajero { get; set; }
        public string Numero { get; set; }
    }
}
